services:
  - type: web
    name: altara-tracking
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /data
    healthCheckPath: /health
    disk:
      name: tracking-data
      mountPath: /data
      sizeGB: 1

